##
# @file 
# @brief Solves the 2nd problem of Project Euler using Python. 
# @author Frank Leveque
# @code
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
# @endcode
# 

## First Fibonacci term
termA = 0
## Second Fibonacci term
termB = 1
## Placeholder for third Fibonacci term resulting from termA + termB
temp = 0 
## Total sum of even Fibonacci terms 
totalEvenSum = 0; 

while (totalEvenSum < 4000000):
    if termB %2==0: 
        totalEvenSum += termB
    
    temp = termA + termB
    termA = termB
    termB = temp

print (totalEvenSum)
